all:
  children:
    infrastructure:
      hosts:
        192.168.1.174
      vars:
        gitlab_admin_password: 'Password123.'
        gitlab_root_password: 'Password123.'
        gitlab_data_dir: /home/ansuser/services/gitlab
        gitlab_image: docker.io/gitlab/gitlab-ce
        gitlab_version: latest
        gitlab_privileged: true
        gitlab_hostname: gitlab
        gitlab_external_url: "http://{{ ansible_host }}"
        gitlab_shm_size: "256m"
        gitlab_memory_limit: "8g"
        gitlab_runner_image: docker.io/gitlab/gitlab-runner
        gitlab_http_port_method: http
        gitlabRunner_default_docker_image: "alpine/ansible:latest"

  vars:
    ansible_user: ansuser
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_become: true
    ansible_become_password: 'MYpeople10.'
